version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      # Check for updates to python deps every week
      interval: "weekly"
