[project]
site_name = "Pyter"
site_description = "Bayesian inference for virological titer data."
site_author = "Dylan H. Morris"
site_url = "https://dylanhmorris.com/pyter"
repo_url = "https://github.com/dylanhmorris/pyter"
repo_name = "pyter"
copyright = "Copyright 2026 Dylan H. Morris"

extra_javascript = [
    "javascripts/mathjax.js",
    "https://unpkg.com/mathjax@4/tex-mml-chtml.js"
]


[project.theme]
language = "en"

features = [
    "announce.dismiss",
    "content.code.annotate",
    "content.code.copy",
    "content.code.select",
    "content.tooltips",
    "content.tabs.link",
    "content.footnote.tooltips",
    "search.highlight",
    "toc.follow",
    "toc.integrate"
]


[project.markdown_extensions.toc]
permalink = true

[project.plugins.offline]

[[project.theme.palette]]
  scheme = "slate"
  toggle.icon = "lucide/sun"
  toggle.name = "Switch to light mode"

[[project.theme.palette]]
  scheme = "default"
  toggle.icon = "lucide/moon"
  toggle.name = "Switch to dark mode"



[project.markdown_extensions.admonition]
[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.pymdownx.superfences]
[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true
[project.markdown_extensions."pymdownx.arithmatex"]
generic = true


[project.plugins.mkdocstrings]
enable_inventory = true

[project.plugins.mkdocstrings.handlers.python]
paths = ["."]
inventories = [
  "https://docs.python.org/3/objects.inv",
  "https://docs.pola.rs/api/python/stable/objects.inv",
  "https://numpy.org/doc/stable/objects.inv",
  "https://num.pyro.ai/en/stable/objects.inv",
  "https://docs.jax.dev/en/latest/objects.inv"
]
[project.plugins.mkdocstrings.handlers.python.options]
annotations_path = "brief"
docstring_style = "numpy"
scoped_crossrefs = true
line_length = 80
separate_signature = true
show_signature_annotations = true
signature_crossrefs = true
merge_init_into_class = true
