name: "Run tests"

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: "Run tests and collect coverage"
    runs-on: ubuntu-latest
    steps:
      - name: "Check out repo"
        uses: "actions/checkout@v4"

      - name: "Run tests"
        run: "uv run pytest test"
